import React, { useState, useEffect, useRef, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Printer, FileText, Download, X, AlertTriangle, Plus, Minus, Eye, RefreshCw } from 'lucide-react';
import JsBarcode from 'jsbarcode';
import { jsPDF } from 'jspdf';
import toast from 'react-hot-toast';
import './ImpresionCodigosBarrasModal.css';

// Predefined configuration values for each size
const SIZES_CONFIG = {
  small: {
    id: 'small',
    name: 'Pequeño (38.1 x 21.2 mm) - 5 Columnas (A4)',
    width: 38.1,
    height: 21.2,
    cols: 5,
    paper: 'A4',
    margin: 10,
    gap: 2
  },
  medium: {
    id: 'medium',
    name: 'Mediano (52.5 x 29.7 mm) - 4 Columnas (A4)',
    width: 52.5,
    height: 29.7,
    cols: 4,
    paper: 'A4',
    margin: 10,
    gap: 2
  },
  large: {
    id: 'large',
    name: 'Grande (70.0 x 37.0 mm) - 3 Columnas (A4)',
    width: 70.0,
    height: 37.0,
    cols: 3,
    paper: 'A4',
    margin: 10,
    gap: 2
  },
  thermal58: {
    id: 'thermal58',
    name: 'Rollo Térmico 58mm (1 Columna)',
    width: 50.0, // printable width inside 58mm
    height: 30.0, // average height per label
    cols: 1,
    paper: 'continuous',
    margin: 2,
    gap: 4
  },
  thermal80: {
    id: 'thermal80',
    name: 'Rollo Térmico 80mm (1 Columna)',
    width: 72.0, // printable width inside 80mm
    height: 40.0, // average height per label
    cols: 1,
    paper: 'continuous',
    margin: 4,
    gap: 4
  }
};

const ImpresionCodigosBarrasModal = ({ open, onClose, productosSeleccionados = [], moneda = 'COP' }) => {
  const [productos, setProductos] = useState([]);
  const [quantities, setQuantities] = useState({});
  const [selectedSize, setSelectedSize] = useState('medium');
  const [showName, setShowName] = useState(true);
  const [showPrice, setShowPrice] = useState(true);
  const [showCode, setShowCode] = useState(true);
  const [generating, setGenerating] = useState(false);
  const barcodeCache = useRef({});

  // Initialize selected products
  useEffect(() => {
    if (open && productosSeleccionados.length > 0) {
      setProductos(productosSeleccionados);
      
      // Default quantities: 1 per product
      const initialQtys = {};
      productosSeleccionados.forEach(p => {
        initialQtys[p.id] = 1;
      });
      setQuantities(initialQtys);
    }
  }, [open, productosSeleccionados]);

  // Clean cache on modal close
  useEffect(() => {
    if (!open) {
      barcodeCache.current = {};
    }
  }, [open]);

  // Get configuration of selected size
  const config = useMemo(() => SIZES_CONFIG[selectedSize], [selectedSize]);

  // Helper to resolve barcode value (handles fallback when code is missing)
  const getBarcodeValue = (product) => {
    if (product.codigo && product.codigo.trim() !== '') {
      return product.codigo.trim();
    }
    // Fallback: Generate a clean identifier based on the product ID or SKU
    const cleanId = String(product.id).replace(/[^0-9]/g, '');
    if (cleanId.length >= 8) {
      return cleanId.substring(0, 12).padEnd(12, '0');
    }
    return `PRD${String(product.id).substring(0, 8).toUpperCase()}`;
  };

  // Generate Base64 Barcode image using a canvas
  const getBarcodeImageBase64 = (value) => {
    if (!value) return '';
    if (barcodeCache.current[value]) {
      return barcodeCache.current[value];
    }

    const canvas = document.createElement('canvas');
    try {
      JsBarcode(canvas, value, {
        format: 'CODE128',
        width: 2,
        height: 40,
        displayValue: false, // Custom label renders text, barcode only renders lines
        margin: 2,
        lineColor: "#000000",
        background: "#ffffff"
      });
      const dataUrl = canvas.toDataURL('image/png');
      barcodeCache.current[value] = dataUrl;
      return dataUrl;
    } catch (err) {
      console.error('Error generating barcode for:', value, err);
      return '';
    }
  };

  // Total quantity of labels to be printed
  const totalLabels = useMemo(() => {
    return productos.reduce((acc, p) => acc + (quantities[p.id] || 0), 0);
  }, [productos, quantities]);

  // Flattened array of labels for rendering in preview grid
  const labelsList = useMemo(() => {
    const list = [];
    productos.forEach(product => {
      const qty = quantities[product.id] || 0;
      const barcodeVal = getBarcodeValue(product);
      const isAutoGenerated = !product.codigo;
      const base64Img = getBarcodeImageBase64(barcodeVal);

      for (let i = 0; i < qty; i++) {
        list.push({
          id: `${product.id}-${i}`,
          product,
          barcodeVal,
          isAutoGenerated,
          base64Img
        });
      }
    });
    return list;
  }, [productos, quantities]);

  // Handle changes in individual quantities
  const handleQtyChange = (productId, val) => {
    const parsed = parseInt(val, 10);
    const checked = isNaN(parsed) || parsed < 0 ? 0 : parsed;
    setQuantities(prev => ({
      ...prev,
      [productId]: checked
    }));
  };

  const handleIncrement = (productId) => {
    setQuantities(prev => ({
      ...prev,
      [productId]: (prev[productId] || 0) + 1
    }));
  };

  const handleDecrement = (productId) => {
    setQuantities(prev => ({
      ...prev,
      [productId]: Math.max(0, (prev[productId] || 0) - 1)
    }));
  };

  // Set all quantities to 1
  const setAllToQtyOne = () => {
    const updated = {};
    productos.forEach(p => {
      updated[p.id] = 1;
    });
    setQuantities(updated);
    toast.success('Cantidad ajustada a 1 para todos los productos');
  };

  // Set all quantities to matches stock
  const setAllToStock = () => {
    const updated = {};
    productos.forEach(p => {
      const stockVal = parseFloat(p.stock || 0);
      const stockInt = Math.max(1, Math.round(stockVal));
      updated[p.id] = stockInt;
    });
    setQuantities(updated);
    toast.success('Cantidades ajustadas según el Stock actual');
  };

  // Remove a product from print list
  const removeProduct = (productId) => {
    setProductos(prev => prev.filter(p => p.id !== productId));
    setQuantities(prev => {
      const updated = { ...prev };
      delete updated[productId];
      return updated;
    });
  };

  // NATIVE PRINT: Uses browser print system
  const handlePrint = () => {
    if (totalLabels === 0) {
      toast.error('No hay etiquetas para imprimir. Ajusta las cantidades.');
      return;
    }
    window.print();
  };

  // PDF EXPORT
  const handleExportPDF = async () => {
    if (totalLabels === 0) {
      toast.error('No hay etiquetas para exportar.');
      return;
    }

    setGenerating(true);
    toast.loading('Generando PDF...', { id: 'pdf-toast' });

    try {
      const { width: labelW, height: labelH, cols, paper, margin, gap } = config;
      let doc;

      if (paper === 'A4') {
        doc = new jsPDF({
          orientation: 'portrait',
          unit: 'mm',
          format: 'a4'
        });

        const paperH = 297;
        let col = 0;
        let row = 0;

        for (let index = 0; index < labelsList.length; index++) {
          const item = labelsList[index];

          // Calculate standard grid layout positions
          const x = margin + col * (labelW + gap);
          const y = margin + row * (labelH + gap);

          // Draw label outline (subtle box)
          doc.setDrawColor(220, 220, 220);
          doc.rect(x, y, labelW, labelH);

          let currentY = y + 3;

          // Draw product name
          let nameLinesCount = 0;
          let calculatedNameFontSize = selectedSize === 'small' ? 6 : 7;
          if (showName) {
            doc.setFont('Helvetica', 'bold');
            if (item.product.nombre.length > 25) {
              calculatedNameFontSize = selectedSize === 'small' ? 5 : 6;
            }
            doc.setFontSize(calculatedNameFontSize);
            const textLines = doc.splitTextToSize(item.product.nombre, labelW - 6);
            const linesToDraw = textLines.slice(0, 3);
            nameLinesCount = linesToDraw.length;
            doc.text(linesToDraw, x + labelW / 2, currentY, { align: 'center' });
            currentY += linesToDraw.length * (calculatedNameFontSize * 0.3527 * 1.25);
          }

          // Draw barcode image
          if (item.base64Img) {
            let imgH = selectedSize === 'small' ? 8 : selectedSize === 'medium' ? 12 : 15;
            // Reduce barcode height if name takes more than 1 line to prevent card overflow
            if (nameLinesCount > 1) {
              const extraLinesHeight = (nameLinesCount - 1) * (calculatedNameFontSize * 0.3527 * 1.25);
              imgH = Math.max(selectedSize === 'small' ? 5 : 8, imgH - extraLinesHeight);
            }
            const imgW = labelW - 6;
            doc.addImage(item.base64Img, 'PNG', x + 3, currentY, imgW, imgH);
            currentY += imgH + 2;
          }

          // Draw price & code numeric
          if (showCode || showPrice) {
            doc.setFont('Helvetica', 'normal');
            doc.setFontSize(selectedSize === 'small' ? 5.5 : 6.5);
            
            let textLine = '';
            if (showCode) textLine += item.barcodeVal;
            if (showPrice) {
              const precioVal = item.product.precio_venta || 0;
              const formattedPrice = `$${precioVal.toLocaleString('es-CO')}`;
              textLine += showCode ? ` | ${formattedPrice}` : formattedPrice;
            }

            doc.text(textLine, x + labelW / 2, currentY, { align: 'center' });
          }

          // Advance column/row
          col++;
          if (col >= cols) {
            col = 0;
            row++;
            
            // Check page overflow
            const maxY = margin + (row + 1) * (labelH + gap);
            if (maxY > paperH - margin && index < labelsList.length - 1) {
              doc.addPage();
              col = 0;
              row = 0;
            }
          }
        }
      } else {
        // Continuous Thermal Roll (e.g. 58mm or 80mm)
        // Each label is an individual page of exact dimension
        const rollW = selectedSize === 'thermal58' ? 58 : 80;
        const rollH = selectedSize === 'thermal58' ? 40 : 50;

        doc = new jsPDF({
          orientation: 'portrait',
          unit: 'mm',
          format: [rollW, rollH]
        });

        for (let index = 0; index < labelsList.length; index++) {
          const item = labelsList[index];

          if (index > 0) {
            doc.addPage([rollW, rollH]);
          }

          // Margins inside roll label
          const x = 3;
          let currentY = 5;
          const usableW = rollW - 6;

          // Border for visual guide
          doc.setDrawColor(240, 240, 240);
          doc.rect(1, 1, rollW - 2, rollH - 2);

          // Name
          let nameLinesCount = 0;
          let calculatedNameFontSize = rollW === 58 ? 8 : 10;
          if (showName) {
            doc.setFont('Helvetica', 'bold');
            if (item.product.nombre.length > 25) {
              calculatedNameFontSize = rollW === 58 ? 7 : 8.5;
            }
            doc.setFontSize(calculatedNameFontSize);
            const textLines = doc.splitTextToSize(item.product.nombre, usableW);
            const linesToDraw = textLines.slice(0, 3);
            nameLinesCount = linesToDraw.length;
            doc.text(linesToDraw, rollW / 2, currentY, { align: 'center' });
            currentY += linesToDraw.length * (calculatedNameFontSize * 0.3527 * 1.25);
          }

          // Barcode
          if (item.base64Img) {
            let imgH = rollW === 58 ? 16 : 22;
            // Reduce barcode height if name takes more than 1 line to prevent label overflow
            if (nameLinesCount > 1) {
              const extraLinesHeight = (nameLinesCount - 1) * (calculatedNameFontSize * 0.3527 * 1.25);
              imgH = Math.max(rollW === 58 ? 10 : 15, imgH - extraLinesHeight);
            }
            doc.addImage(item.base64Img, 'PNG', x, currentY, usableW, imgH);
            currentY += imgH + 3.5;
          }

          // Price & Code
          if (showCode || showPrice) {
            doc.setFont('Helvetica', 'bold');
            doc.setFontSize(rollW === 58 ? 7.5 : 9.5);
            
            let textLine = '';
            if (showCode) textLine += item.barcodeVal;
            if (showPrice) {
              const precioVal = item.product.precio_venta || 0;
              const formattedPrice = `$${precioVal.toLocaleString('es-CO')}`;
              textLine += showCode ? `   ${formattedPrice}` : formattedPrice;
            }

            doc.text(textLine, rollW / 2, currentY, { align: 'center' });
          }
        }
      }

      // Download file
      doc.save(`codigos_barra_${new Date().getTime()}.pdf`);
      toast.success('Documento PDF descargado correctamente', { id: 'pdf-toast' });
    } catch (err) {
      console.error(err);
      toast.error('Error al generar el PDF', { id: 'pdf-toast' });
    } finally {
      setGenerating(false);
    }
  };

  // WORD EXPORT (Generates HTML compatible table with Base64 images)
  const handleExportWord = () => {
    if (totalLabels === 0) {
      toast.error('No hay etiquetas para exportar.');
      return;
    }

    try {
      const { name, cols, width, height } = config;
      
      let htmlString = `
        <html xmlns:o='urn:schemas-microsoft-com:office:office' 
              xmlns:w='urn:schemas-microsoft-com:office:word' 
              xmlns='http://www.w3.org/TR/REC-html40'>
        <head>
          <title>Códigos de Barra - Crece Más</title>
          <!--[if gte mso 9]>
          <xml>
            <w:WordDocument>
              <w:View>Print</w:View>
              <w:Zoom>100</w:Zoom>
            </w:WordDocument>
          </xml>
          <![endif]-->
          <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            table { width: 100%; border-collapse: collapse; table-layout: fixed; }
            td { 
              border: 1px dashed #cccccc; 
              width: ${width}mm; 
              height: ${height}mm; 
              padding: 6px; 
              text-align: center; 
              vertical-align: middle; 
              word-wrap: break-word;
            }
            .label-name { font-size: 8pt; font-weight: bold; margin-bottom: 3px; }
            .label-img { max-width: 90%; height: auto; display: block; margin: 0 auto; }
            .label-info { font-size: 7.5pt; margin-top: 3px; }
            .price { font-weight: bold; }
          </style>
        </head>
        <body>
          <h2>Reporte de Códigos de Barras (${name})</h2>
          <table>
            <tr>
      `;

      let colCount = 0;

      labelsList.forEach((item, index) => {
        // Build label cell
        htmlString += `<td>`;
        
        if (showName) {
          htmlString += `<div class="label-name">${item.product.nombre}</div>`;
        }

        if (item.base64Img) {
          htmlString += `<img class="label-img" src="${item.base64Img}" alt="${item.barcodeVal}" width="${width * 3}" />`;
        }

        if (showCode || showPrice) {
          htmlString += `<div class="label-info">`;
          if (showCode) htmlString += `<span class="code">${item.barcodeVal}</span>`;
          if (showPrice) {
            const price = item.product.precio_venta || 0;
            const formatted = `$${price.toLocaleString('es-CO')}`;
            htmlString += showCode ? ` - <span class="price">${formatted}</span>` : `<span class="price">${formatted}</span>`;
          }
          htmlString += `</div>`;
        }

        htmlString += `</td>`;

        colCount++;
        if (colCount >= cols) {
          colCount = 0;
          htmlString += `</tr><tr>`;
        }
      });

      // Complete last row if needed
      if (colCount > 0) {
        while (colCount < cols) {
          htmlString += `<td>&nbsp;</td>`;
          colCount++;
        }
        htmlString += `</tr>`;
      } else {
        // Remove trailing empty <tr>
        htmlString = htmlString.substring(0, htmlString.length - 4);
      }

      htmlString += `
          </table>
        </body>
        </html>
      `;

      // Create download link for doc format
      const blob = new Blob([htmlString], { type: 'application/msword;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `codigos_barra_${new Date().getTime()}.doc`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      toast.success('Documento Word descargado correctamente');
    } catch (err) {
      console.error(err);
      toast.error('Error al exportar a Word');
    }
  };

  if (!open) return null;

  return (
    <AnimatePresence>
      <div className="barcodes-modal-overlay">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 15 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 15 }}
          className="barcodes-modal-container"
        >
          {/* Header */}
          <div className="barcodes-modal-header">
            <h2>
              <Printer size={22} className="text-primary" />
              <span>Generador de Códigos de Barras e Impresión</span>
            </h2>
            <button className="close-modal-btn" onClick={onClose} aria-label="Cerrar">
              <X size={20} />
            </button>
          </div>

          {/* Body */}
          <div className="barcodes-modal-content">
            
            {/* Left: Settings & Products */}
            <div className="barcodes-left-panel">
              
              {/* Configurations section */}
              <div className="barcodes-config-grid">
                <div className="config-group">
                  <label htmlFor="label-size-select">Tamaño y Diseño de Etiqueta</label>
                  <select
                    id="label-size-select"
                    className="config-select"
                    value={selectedSize}
                    onChange={(e) => setSelectedSize(e.target.value)}
                  >
                    {Object.values(SIZES_CONFIG).map(s => (
                      <option key={s.id} value={s.id}>{s.name}</option>
                    ))}
                  </select>
                </div>

                <div className="config-group">
                  <label>Campos en la Etiqueta</label>
                  <div className="config-checkbox-group">
                    <label className="config-checkbox-label">
                      <input
                        type="checkbox"
                        checked={showName}
                        onChange={(e) => setShowName(e.target.checked)}
                      />
                      <span>Nombre</span>
                    </label>
                    <label className="config-checkbox-label">
                      <input
                        type="checkbox"
                        checked={showPrice}
                        onChange={(e) => setShowPrice(e.target.checked)}
                      />
                      <span>Precio</span>
                    </label>
                    <label className="config-checkbox-label">
                      <input
                        type="checkbox"
                        checked={showCode}
                        onChange={(e) => setShowCode(e.target.checked)}
                      />
                      <span>Código</span>
                    </label>
                  </div>
                </div>

                <div className="config-group">
                  <label>Configuración Rápida de Cantidades</label>
                  <div className="bulk-fill-row">
                    <button className="btn-bulk" onClick={setAllToQtyOne} type="button">
                      Todos = 1
                    </button>
                    <button className="btn-bulk" onClick={setAllToStock} type="button">
                      Todos = Stock
                    </button>
                  </div>
                </div>
              </div>

              {/* Products Table */}
              <div className="barcodes-products-section">
                <h3>Productos en Lista ({productos.length})</h3>
                <div className="table-container">
                  <table className="barcodes-table">
                    <thead>
                      <tr>
                        <th>Producto</th>
                        <th style={{ width: '80px', textAlign: 'center' }}>Stock</th>
                        <th style={{ width: '130px', textAlign: 'center' }}>Etiquetas a Imprimir</th>
                        <th style={{ width: '50px' }}></th>
                      </tr>
                    </thead>
                    <tbody>
                      {productos.map(p => {
                        const barcode = getBarcodeValue(p);
                        const isAutoGenerated = !p.codigo;

                        return (
                          <tr key={p.id}>
                            <td>
                              <div className="prod-cell-info">
                                <img
                                  src={p.imagen || 'https://via.placeholder.com/40'}
                                  alt={p.nombre}
                                  className="prod-cell-img"
                                  onError={(e) => {
                                    e.target.src = 'https://via.placeholder.com/40';
                                  }}
                                />
                                <div>
                                  <div className="prod-cell-name">{p.nombre}</div>
                                  <div className="prod-cell-code">
                                    {isAutoGenerated ? (
                                      <span className="warning-no-code" title="Este producto no tiene código. Se auto-generó uno temporal para el código de barras.">
                                        Generado: {barcode}
                                      </span>
                                    ) : (
                                      <span>Código: {barcode}</span>
                                    )}
                                  </div>
                                </div>
                              </div>
                            </td>
                            <td style={{ textAlign: 'center', fontWeight: '500' }}>
                              {p.stock !== null && p.stock !== undefined ? Math.round(parseFloat(p.stock)) : '0'}
                            </td>
                            <td>
                              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px' }}>
                                <button
                                  type="button"
                                  className="btn-bulk"
                                  style={{ padding: '4px 8px' }}
                                  onClick={() => handleDecrement(p.id)}
                                >
                                  <Minus size={12} />
                                </button>
                                <input
                                  type="number"
                                  min="0"
                                  className="qty-input"
                                  value={quantities[p.id] !== undefined ? quantities[p.id] : 1}
                                  onChange={(e) => handleQtyChange(p.id, e.target.value)}
                                />
                                <button
                                  type="button"
                                  className="btn-bulk"
                                  style={{ padding: '4px 8px' }}
                                  onClick={() => handleIncrement(p.id)}
                                >
                                  <Plus size={12} />
                                </button>
                              </div>
                            </td>
                            <td style={{ textAlign: 'center' }}>
                              <button
                                type="button"
                                className="btn-remove-prod"
                                onClick={() => removeProduct(p.id)}
                                title="Quitar de la lista"
                              >
                                <X size={16} />
                              </button>
                            </td>
                          </tr>
                        );
                      })}
                      {productos.length === 0 && (
                        <tr>
                          <td colSpan="4" style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-secondary)' }}>
                            No hay productos en la lista. Cierra el modal y selecciona productos.
                          </td>
                        </tr>
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>

            {/* Right: Live Preview */}
            <div className="barcodes-right-panel">
              <div className="barcodes-preview-header">
                <span>Vista Previa del Papel ({totalLabels} etiquetas)</span>
                <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <Eye size={14} /> Reflejo dinámico
                </span>
              </div>
              <div className="barcodes-preview-scroll">
                {totalLabels > 0 ? (
                  <div
                    id="printable-barcode-area"
                    className={`paper-sheet-preview size-${config.id}`}
                  >
                    <div className="labels-grid">
                      {labelsList.map((item, idx) => (
                        <div key={item.id} className="barcode-label-card">
                          {showName && (
                            <div className="label-product-name">
                              {item.product.nombre}
                            </div>
                          )}
                          
                          {item.base64Img && (
                            <img
                              src={item.base64Img}
                              alt={item.barcodeVal}
                              className="label-barcode-img"
                            />
                          )}

                          {(showCode || showPrice) && (
                            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1px', width: '100%' }}>
                              {showCode && (
                                <span style={{ fontSize: '6pt', letterSpacing: '0.5px', fontFamily: 'monospace' }}>
                                  {item.barcodeVal}
                                </span>
                              )}
                              {showPrice && (
                                <span className="label-price">
                                  ${(item.product.precio_venta || 0).toLocaleString('es-CO')}
                                </span>
                              )}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                ) : (
                  <div className="empty-preview-state">
                    <AlertTriangle size={36} color="#d97706" />
                    <p style={{ fontWeight: 600 }}>Vista previa vacía</p>
                    <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', maxWidth: '240px', margin: 0 }}>
                      Asigna al menos una cantidad de etiquetas a imprimir para ver la distribución del espacio en papel.
                    </p>
                  </div>
                )}
              </div>
            </div>

          </div>

          {/* Footer Actions */}
          <div className="barcodes-modal-footer">
            <button className="btn-close-footer" onClick={onClose}>
              Cancelar
            </button>
            <button
              className="btn-action-secondary"
              onClick={handleExportWord}
              disabled={totalLabels === 0}
              title="Guardar archivo .doc compatible con Microsoft Word"
            >
              <FileText size={18} />
              <span>Guardar Word</span>
            </button>
            <button
              className="btn-action-secondary"
              onClick={handleExportPDF}
              disabled={totalLabels === 0 || generating}
            >
              {generating ? <RefreshCw size={18} className="spin" /> : <Download size={18} />}
              <span>Guardar PDF</span>
            </button>
            <button
              className="btn-action-primary"
              onClick={handlePrint}
              disabled={totalLabels === 0}
            >
              <Printer size={18} />
              <span>Imprimir Códigos</span>
            </button>
          </div>

        </motion.div>
      </div>
    </AnimatePresence>
  );
};

export default ImpresionCodigosBarrasModal;
